# Generated by Django 5.0.6 on 2024-06-30 01:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carritoproducto',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='total',
        ),
        migrations.AddField(
            model_name='carrito',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carritoproducto',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='pagina_mascotas.carrito'),
        ),
    ]
